name: simple_calcutor_with_getx
description: getx flex
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Digital-7
      fonts:
        - asset: assets/fonts/digital-7/digital-7.ttf
        - asset: assets/fonts/digital-7/digital-7-itallic.ttf
          style: italic
        - asset: assets/fonts/digital-7/digital-7-mono.ttf
          weight: 500


